### ISSUE TITLE
As a potential player, I want to be able to update my profile with a name, email, and picture, so that I can personalize my gaming experience and save my scores from the game.

### ISSUE THREAD

**Issue by rogerjeasy** [sopra-fs24-group-32/sopra-fs24-group-32-server#1]
**Acceptance Criteria**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#21
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#22
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#23
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#24
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#25
