### ISSUE TITLE
As a game host, I want to be able to kick players that joined the lobby to maintain a positive and respectful environment before the game starts.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#10]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#94
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#49
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#96
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#50
