### ISSUE TITLE
As a player, I want my guesses to be automatically assessed for correctness by ChatGPT, so that the game can fairly and efficiently award points based on accurate assessments.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#14]
**Acceptance Criteria:**
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#55
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#81
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#82
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#83
