### ISSUE TITLE
As a player, at the end of all rounds, I want to see the final rankings based on points, so that I know the outcome of the game and see how I and others performed.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#18]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#42
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#40
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#41
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#59

**Comment by eduard54** [comment]
commit: 7387f6a
