### ISSUE TITLE
As the host, after the game has finished, I want the option to either play another game with the same lobby or close the lobby, to either continue playing or end the session.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#20]
**Acceptance Criteria**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#90
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#51
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#52
