### ISSUE TITLE
As a logged-in player, I want to create a new lobby, so that I can invite my friends.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#3]
**Acceptance Criteria**
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#26
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#30
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#27
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#28
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#29
