### ISSUE TITLE
As a game host, I want to limit the number of players that can participate in a game session, so that the game remains manageable, enjoyable, and within the optimal performance parameters (optional).

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#4]
**Acceptance Criteria**
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#43
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#44
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#39
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#40
additional players to join, regardless of whether players leave the lobby later.
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#41
