### ISSUE TITLE
As a logged-in player, I want to join an existing lobby, so that I can join a game session.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#5]
**Acceptance Criteria**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#57
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#100
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#101
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#102
additional players to join, regardless of whether players leave the lobby later.
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#58
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#56
