### ISSUE TITLE
As a game host, I want to specify the number of rounds that are required to play to determine the winner and customize the game length according to player preferences and availability.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-server#6]
**Acceptance Criteria:**
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-client#1
- [ ] #98
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#44
- [ ] sopra-fs24-group-32/sopra-fs24-group-32-server#45

**Comment by eduard54** [comment]
commit: 71fa2cf
